### ISSUE TITLE
Feature: Glob patterns for values in `trace.dynamic.resolutions`

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/serverless-jetpack#116]
Could glob resolution values _after_ have misses because then could match `@heroku/socksv5/index.js` to `../node_modules/@heroku/socksv5/index.js` but would need to do a second pass `traceFiles`.

So, instead of:

```yml
resolutions:
  "@heroku/socksv5/index.js":
    - "./lib/constants.js"
    - "./lib/client.js"
    - "./lib/server.parser.js"
    - "./lib/Agents.js"
    - "./lib/auth/UserPassword.js"
    - "./lib/auth/None.js"
    - "./lib/server.js"
    - "./lib/utils.js"
```

Allow this:

```yml
resolutions:
  "@heroku/socksv5/index.js":
    - "./lib/**/*.js"
```

**Comment by dominics** [comment]
@ryan-roemer Glob patterns for allowMissing would also be appreciated; would potentially allow me a different workaround at https://github.com/dominics/issue-jp-sh/blob/main/serverless.yml#L36 (for issue explained in that repo's README)

**Comment by ryan-roemer** [comment]
Hi @dominics ! I'm still wrangling how best to write this feature / refactor things because globs _do_ work for relative paths if you know the root path (like where `node_modules/@heroku/socksv5/index.js` ended up on disk), but things that aren't directly relative (e.g., `./`. `../`) and use the Node.js `require()` algorithm are a lot harder to reason about because a glob can't be passed to `resolve()` and produce an absolute path.

Let's see if we can maybe get you passed your current use case with something simpler -- what is the error if you remove all `ignores` and `allowMissing` for `sanitize-html`?

I'm not clear on the long list of extra files to resolve you have in that `allowMissing`. Looking at the source in https://unpkg.com/sanitize-html@1.27.3/dist/sanitize-html.js what my guess is is that you have a browserified file that is meant for execution in the browser that uses _browserify_, not node's `require` and that's causing the issues. For example, in that file we have:

```js
// Require apply from lodash
require('./_apply')

// Here's the mapping to internal browserify structure
{"./_apply":44}

// At 44, we see this chunk of code (which I've prettified a bit):
44: [
function(require,module,exports){/**
 * A faster alternative to `Function#apply`, this function invokes `func`
 * with the `this` binding of `thisArg` and the arguments of `args`.
 *
 * @private
 * @param {Function} func The function to invoke.
 * @param {*} thisArg The `this` binding of `func`.
 * @param {Array} args The arguments to invoke `func` with.
 * @returns {*} Returns the result of `func`.
 */
function apply(func,thisArg,args) {
  switch(args.length){
    case 0:return func.call(thisArg);
    case 1:return func.call(thisArg,args[0]);
    case 2:return func.call(thisArg,args[0],args[1]);
    case 3:return func.call(thisArg,args[0],args[1],args[2]);
  }
  return func.apply(thisArg,args);
}
module.exports=apply;
},{}]
```

... and it _does_ look like that that is the real lodash apply code within `sanitize-html` bundle that you'd normally find here: https://unpkg.com/lodash@4.17.20/_apply.js. So, this all means that the missing require's you're adding to `allowMissing` are actual files (like, you've got `./_apply.js` there, but that's meant to be from within lodash code, not at the level of `sanitize-html`).

My guess is that all of the four dependencies specified at https://github.com/apostrophecms/sanitize-html/blob/main/package.json#L29-L32 **are** actually included in that browserified bundle and you should be fine. Upon spot checking, lodash and postcss appear. 

So, I think your first workaround is fine, but it does have one issue in that if `sanitize-html` moves around in how it lands on disk from yarn/npm flattening that direct path may change. I'd recommend switching to `trace.dynamic.resolutions` instead of `allowMissing` and `package.include` with something like the following:

```yml
my-handler:
  handler: index.handler
  jetpack:
    trace:
      dynamic:
        resolutions:
          # All dependencies are included in browserified bundle
          "sanitize-html": false
```

However, if you really wanted a "belt-and-suspenders" approach you could probably just add dynamic resolutions of all of the production `package.json:dependencies` of the library itself just to be sure:

```yml
my-handler:
  handler: index.handler
  jetpack:
    trace:
      dynamic:
        resolutions:
          # Just to be sure, manually trace all dependencies from package.json
          # https://github.com/apostrophecms/sanitize-html/blob/main/package.json#L29-L32
          "sanitize-html":
            - "htmlparser2"
            - "lodash"
            - "parse-srcset"
            - "postcss"
```

Hope that helps!
