### ISSUE TITLE
[Question] How to properly configure monorepo Typescript project?

### ISSUE THREAD

**Issue by vamcs** [FormidableLabs/serverless-jetpack#141]
I got tired of `serverless-webpack` being too complex to set up with a monorepo and decided to try `serverless-jetpack` instead. 

Two questions:
1) Would it work to use jetpack in a monorepo where each service has its own `serverless.yml`?
2) Could you provide a more complete example with Typescript?

I've read through #74 and started using `serverless-scriptable-plugin` with a manual build with `tsc` but I don't quite get what to include or exclude and where to do that.

Additional question: is there any sort of tree shaking going on? If I have the structure below and if I pack each function individually will I only get the (transpilled) `get.js` file in the `get` function bundle? Or do I have to explicitly exclude everything else and only include that file for that function?

```
services/
  service1/
    get.ts
    create.ts
```

Thanks a lot!

**Comment by ryan-roemer** [comment]
Hi @vamcs !

We've got lots of clients doing both monorepos + TS with various different setups.

I'd definitely recommend using tracing mode, although there is more configuration involved than legacy mode.

## Building TS

Jetpack only reads real JS files that Node.js can read. So you'll want to build your TS and point a serverless handler at that file.

What we normally do in our monorepos is have the root `package.json` just have a `scripts` task like `build:ts` or something that builds everything once, effectively separating the TS build from the serverless packaging. So basically the strategy is "make sure TS is build _before_ running any serverless commands".

This is nice because then serverless `package|deploy` doesn't have a mandatory build step, which you don't always need. But, if you want it to be part of the lifecycle, the `serverless-scriptable-plugin` example will probably work fine.

So assuming TS is already built (with a transpiled JavaScript entry point at like `services/{NAME}/dist/{ENTRY}.js` or something), let's look at ways of serverless package/deploy:

## OPTION ONE -- Single Config

This is what we most typically do. Create a root-level `serverless.yml` config like the following:

```yml
service: SERVICE_NAME

custom:
  jetpack:
    concurrency: 4    # If you're on a Multi-CPU machine consider setting this to package in parallel.
    collapsed:
      bail: true      # (OPTIONAL) Abort build if collapsed files in zip. (Sometimes an issue in monorepos).
    preInclude:
      - "!**"         # Start with no files at all.
    trace:            # Trace actual dependencies at each entry point
      dynamic:
        bail: true    # (OPTIONAL) Abort build if untraceable imports.

package:
  individually: true  # Package each function individually

plugins:
  modules:
    - serverless-jetpack

provider: # ...

functions:
  service1:
    # Transpiled JS file at: services/service1/dist/{ENTRY}.js
    handler: services/service1/dist/{ENTRY}.{HANDLER_NAME}

  service2:
    handler: services/service2/dist/{ENTRY}.{HANDLER_NAME}
  
  # ...
```

To your "tree shaking" comment, this approach won't remove any unused code paths as it doesn't _transform_ any source files. But it does trace and **only** include the files that are imported anywhere transitively starting at the entry point. In our experience, this ends up being not noticeably larger than an equivalent webpack build and often much nicer for things like debugging because you get stack traces from the real, original source files, etc.

## OPTION TWO -- Multiple Configs

You could also place individual config in something like `services/{NAME}/serverless.yml`. You then wouldn't need to package with `package.individually = true` because there would be only one function per config.

But you would want to look at serverless config include features to avoid a lot of duplication. And if you wanted things like concurrent builds you'd have to script that yourself.

## Assessment

Tracing mode normally needs some extra options for imports that can't be directly inferred, so I've given you a config with two `bail = true` safety guards to fail the build if potential correctness issues are detected (and some of these things are _not_ detected by webpack, so you may discover new runtime dependencies). In particular, you'll likely need some work with issues like https://github.com/FormidableLabs/serverless-jetpack#handling-dynamic-import-misses

Most configs end up with some combination of: 

```
jetpack:
    concurrency: 2

    trace:
      # Manually add other JS files to trace from to include in a bundle.
      include:
        # ...
      
      # Completely ignore certain imports.
      ignores:
        # ...
        # Unconditionally skip `aws-sdk` and all dependencies
        # (Because already installed in target Lambda)
        - "aws-sdk"
      
      # Specify import misses that are anticipated and allowed.
      allowMissing: 
        # ...

      dynamic:
        # Explicitly handle all dynamic import misses by ignoring or adding
        # additional files to trace.
        #
        # See: https://npm.im/serverless-jetpack#handling-dynamic-import-misses
        resolutions:
          # ...
```

I do realize this is a bit of config to bite off from the relative simplicity of the webpack plugin, but once you've got the hang of things we'll hope you like it -- we've had pretty good responses from folks switching from the webpack plugin to Jetpack.

And if you're encountering config issues getting started with Jetpack, feel free to drop them in here on this issue or create a public, minimal repo to replicate the structural problem you're trying to solve and I can jump in. 

Cheers and good luck!
