### ISSUE TITLE
Erratic build times and `include` / `exclude` inconsistent behaviour

### ISSUE THREAD

**Issue by nfantone** [FormidableLabs/serverless-jetpack#52]
## Internal work tracking

- [ ] README: Review and update suggested "good/best" practices for `!PATTERN` vs `!PATTERN/**` (aka "double exclusion" pattern)
- [ ] README: See if any other sections need double exclusion update.
- [ ] Test Fixtures: See if we can do an "exclude everything" configuration that is equivalent in jetpack and `serverless`. Also assess efficiency (given limitations of exclude).

## Original Issue

Hi! Today, I stumbled upon this plugin and given how poorly `serverless` own `package` seems to perform in most situations, and the number of times dev dependencies end up, needlessly, in our builds, I decided to give it shot.

After setting things up, I encountered some seemingly abnormal behaviours.

1) Builds times are completely erratic. In the service I was testing the plugin in, they go from ~25s to almost ~4m (!), and everything in between. Below are consecutive runs (same configuration, default plugin options), one after the other.

```sh
# Almost four minutes (first run)
Serverless: [serverless-jetpack] Packaging 0 functions, 1 services, and 0 layers with concurrency 1
Serverless: [serverless-jetpack] Packaged service: .serverless/test-service.zip (213.31s)

# 25 seconds
Serverless: [serverless-jetpack] Packaging 0 functions, 1 services, and 0 layers with concurrency 1
Serverless: [serverless-jetpack] Packaged service: .serverless/test-service.zip (25.25s)

# A minute and a half
Serverless: [serverless-jetpack] Packaging 0 functions, 1 services, and 0 layers with concurrency 1
Serverless: [serverless-jetpack] Packaged service: .serverless/test-service.zip (80.81s)

# Half a minute
Serverless: [serverless-jetpack] Packaging 0 functions, 1 services, and 0 layers with concurrency 1
Serverless: [serverless-jetpack] Packaged service: .serverless/test-service.zip (28.93s)
```

This is running locally, on a macOS Mojave 10.14.5 (18F203) MBP laptop.

2) Following [the `README.md` advice on best practices](https://github.com/FormidableLabs/serverless-jetpack#be-careful-with-include-configurations-and-node_modules), I added a `'!**/node_modules/aws-sdk'` entry under `include` (along with a bunch more). 

```yml
package:
  excludeDevDependencies: true
  include:
    - build/**
    - package.json
    - '!**/node_modules/aws-sdk'
    - '!**/node_modules/@types'
    - '!**/node_modules/@babel'
    - '!build/**/*.test.js'
```

However, checking final `.zip` bundle reveals the following:

```sh
❯ ls -lta .serverless/test-service/node_modules | grep -E 'aws-sdk|@babel|@types'
drwxr-xr-x   22 nfantone  staff    704 17 Jul 20:27 aws-sdk
drwxr-xr-x    3 nfantone  staff     96 17 Jul 20:27 @babel
```

You can see `node_modules/@types` is correctly ignored, but `aws-sdk` and `@babel` are still included in the bundle. I'm guessing this is because some transitive dependency is requiring modules inside those packages? If that's the case, I believe they should still be ignored as per configuration?

3) Using original `serverless package`, I was using `*` and `*/**` with `exclude` to ignore everything _not explicitly declared under `include`_. And that was producing the expected output. With `jetpack` I can't seem to get that to work. Setting:

```yml
exclude:
  - '*'
  - '*/**'
```

Also excludes `node_modules` + it makes packaging _way_ slower. How should I go about this, taking also performance into account?

Thanks so much in advance!

**Comment by ryan-roemer** [comment]
Can you provide a minimal repository with install + build instructions so that I can reproduce the issue? 

In the meantime, the only thing offhand I see is that we probably need to update the docs to a more robust usage like here: https://github.com/FormidableLabs/aws-lambda-serverless-reference/blob/master/serverless.yml#L4-L28

... so for your setup maybe something like:

```yml
package:
  # (unneeded) excludeDevDependencies: true
  include:
    - build/**
    - package.json
    - '!**/node_modules/aws-sdk'
    - '!**/node_modules/aws-sdk/**'
    - '!**/node_modules/@types'
    - '!**/node_modules/@types/**'
    - '!**/node_modules/@babel'
    - '!**/node_modules/@babel/**'
    - '!build/**/*.test.js'
```
