### ISSUE TITLE
BUG: Serverless is no longer creating wrapper functions for serverless dashboard

### ISSUE THREAD

**Issue by cbumstead** [FormidableLabs/serverless-jetpack#67]
Serverless dashboard creates wrapper functions for the handler methods which contains metadata used for logging lambda invocations.    When serverless-jetpack plugin is used these wrapper functions do not get created and the lambda functions end up failing because the files and functions no longer exist.  These functions are prefixed with `s_` like `s_my_function.js`

To enable dashboard on an existing serverless project add app and tenant:

```yml
  # serverless.yml
  app: my-app
  tenant: my-company
```

**Comment by ryan-roemer** [comment]
Thanks for the bug report! So if I take a demo project and add those two lines I will hit the issue?

If so, how do I confirm I’ve hit the issue programmatically or inspection-wise?

**Comment by cbumstead** [comment]
Good question.  The easiest way is to first create a simple serverless dashboard project without jetpack plugin with a single function.

```yml
# serverless.yml

service: test-service
app: my-app
tenant: my-company
    
provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2

functions:
  test:
    handler: handler.test
```

```javascript
// handler.js

modules.exports = { test: (event, context) => return 'hello' }

```
Then run `serverless deploy` and notice that an s_test.js file is created.
Delete the s_test.js file.
Then add the jetpack plugin and run `serverless deploy` and notice the wrapper file is not generated.
