### ISSUE TITLE
serverless-jetpack doesn't see my functions when packaging

### ISSUE THREAD

**Issue by khaledosman** [FormidableLabs/serverless-jetpack#77]
serverless.yml config file: (I omitted the iamRoles, environment sections and some extra functions to reduce noise)
```yml
service:
  name: ovs-backend
app: ovs
org: colorfy

custom:
  aws_profile: "ovs"
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}
  serverless-jetpack:
    mode: "yarn" # (default `yarn`)
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    forceExclude:
      - aws-sdk
    packager: "yarn"
    packagerOptions:
      scripts:
        - yarn autoclean --init
        - cat ../../.yarnclean >> .yarnclean
        - yarn autoclean --force
  prune:
    automatic: true
    number: 5 # Number of versions to keep

  # warmup:
  #   prewarm: true
  #   name: ${self:service}-${self:provider.stage}-lambda-warmer
  #   concurrency: 1

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  # - serverless-plugin-warmup
  - serverless-webpack
  - serverless-jetpack
  - serverless-prune-plugin
  - serverless-plugin-select

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.aws_profile} # aws credentials profile to use
  region: ${opt:region, 'eu-central-1'}
  apiGateway:
    minimumCompressionSize: 1024
  tracing:
    apiGateway: true
    lambda: true

package: # Optional deployment packaging configuration
  # include: # Specify the directories and files which should be included in the deployment package
  # - src/**
  # - handler.js
  individually: true
  exclude: # Specify the directories and files which should be excluded in the deployment package
    - .git/**
    - env.yml
    - package-lock.json
    - yarn.lock
    - .env
    - "*.md"
    - responses/**
    - .vscode/**
    - "*.config.js"
  excludeDevDependencies: true

functions:
  sendTestNotification:
    handler: api/sendTestNotification.handler
    stages:
      - dev
    events:
      - http:
          path: sendTestNotification
          method: get

  graphqlHandler:
    handler: api/graphqlHandler.graphqlHandler
    provisionedConcurrency: 4
    timeout: 20
    events:
      - http:
          path: playground
          method: get
          cors: true
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

```
A full SLS_DEBUG="*" serverless package terminal dump
```bash
➜  ovs-lambdas git:(master) SLS_DEBUG="*" sls package
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command webpack
Serverless: Load command jetpack
Serverless: Load command jetpack:package
Serverless: Load command prune
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
platform-sdk fetching: POST https://api.serverless.com/core/tenants/colorfy/applications/ovs/profileValue
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Select: selecting functions for deployment
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 5566ms
Built at: 2020-01-23 16:32:01
                          Asset      Size
    api/sendTestNotification.js  3.71 KiB  [emitted]        [name: api/sendTestNotification]
api/sendTestNotification.js.map  7.62 KiB  [emitted] [dev]  [name: (api/sendTestNotification)]
     public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/sendTestNotification = api/sendTestNotification.js (api/sendTestNotification.js.map)
./api/sendTestNotification.ts + 2 modules 2.37 KiB [built]
external "googleapis" 42 bytes [built]
external "axios" 42 bytes [built]
./ovs-app-firebase-adminsdk-b9hfq-04afa17dbf.json 2.24 KiB [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
    + 4 hidden modules
Time: 6941ms
Built at: 2020-01-23 16:32:02
                         Asset      Size
    api/deleteOldDataFromDb.js  9.76 KiB  [emitted]        [name: api/deleteOldDataFromDb]
api/deleteOldDataFromDb.js.map  36.1 KiB  [emitted] [dev]  [name: (api/deleteOldDataFromDb)]
    public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/deleteOldDataFromDb = api/deleteOldDataFromDb.js (api/deleteOldDataFromDb.js.map)
./api/deleteOldDataFromDb.ts + 20 modules 18.6 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "mongoose" 42 bytes [built]
    + 4 hidden modules
Time: 7810ms
Built at: 2020-01-23 16:32:03
                                  Asset      Size
    api/syncDatabaseWithGamesHandler.js  14.6 KiB  [emitted]        [name: api/syncDatabaseWithGamesHandler]
api/syncDatabaseWithGamesHandler.js.map  54.7 KiB  [emitted] [dev]  [name: (api/syncDatabaseWithGamesHandler)]
             public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/syncDatabaseWithGamesHandler = api/syncDatabaseWithGamesHandler.js (api/syncDatabaseWithGamesHandler.js.map)
./api/syncDatabaseWithGamesHandler.ts + 21 modules 31.3 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "mongoose" 42 bytes [built]
external "axios" 42 bytes [built]
    + 4 hidden modules
Time: 7923ms
Built at: 2020-01-23 16:32:03
                           Asset      Size
    api/syncDatabaseWithTeams.js  14.6 KiB  [emitted]        [name: api/syncDatabaseWithTeams]
api/syncDatabaseWithTeams.js.map  57.3 KiB  [emitted] [dev]  [name: (api/syncDatabaseWithTeams)]
      public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/syncDatabaseWithTeams = api/syncDatabaseWithTeams.js (api/syncDatabaseWithTeams.js.map)
./api/syncDatabaseWithTeams.ts + 21 modules 33.1 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "mongoose" 42 bytes [built]
external "axios" 42 bytes [built]
    + 4 hidden modules
Time: 7605ms
Built at: 2020-01-23 16:32:03
                          Asset      Size
    api/syncDatabaseWithOdds.js  10.6 KiB  [emitted]        [name: api/syncDatabaseWithOdds]
api/syncDatabaseWithOdds.js.map  48.9 KiB  [emitted] [dev]  [name: (api/syncDatabaseWithOdds)]
     public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/syncDatabaseWithOdds = api/syncDatabaseWithOdds.js (api/syncDatabaseWithOdds.js.map)
./api/syncDatabaseWithOdds.ts + 21 modules 29 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "mongoose" 42 bytes [built]
external "axios" 42 bytes [built]
    + 4 hidden modules
Time: 7155ms
Built at: 2020-01-23 16:32:02
                                 Asset      Size
    api/syncDatabaseWithAYWTHandler.js   9.9 KiB  [emitted]        [name: api/syncDatabaseWithAYWTHandler]
api/syncDatabaseWithAYWTHandler.js.map  40.1 KiB  [emitted] [dev]  [name: (api/syncDatabaseWithAYWTHandler)]
            public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/syncDatabaseWithAYWTHandler = api/syncDatabaseWithAYWTHandler.js (api/syncDatabaseWithAYWTHandler.js.map)
./api/syncDatabaseWithAYWTHandler.ts + 21 modules 20.5 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "mongoose" 42 bytes [built]
external "axios" 42 bytes [built]
    + 4 hidden modules
Time: 7484ms
Built at: 2020-01-23 16:32:03
                        Asset      Size
    api/excitometerChecker.js  11.8 KiB  [emitted]        [name: api/excitometerChecker]
api/excitometerChecker.js.map  45.8 KiB  [emitted] [dev]  [name: (api/excitometerChecker)]
   public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/excitometerChecker = api/excitometerChecker.js (api/excitometerChecker.js.map)
./api/excitometerChecker.ts + 22 modules 24.4 KiB [built]
external "ioredis" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "mongoose" 42 bytes [built]
external "axios" 42 bytes [built]
external "aws-sdk/clients/sqs" 42 bytes [built]
    + 4 hidden modules
Time: 5544ms
Built at: 2020-01-23 16:32:01
                                 Asset      Size
    api/sendPushNotificationHandler.js  3.67 KiB  [emitted]        [name: api/sendPushNotificationHandler]
api/sendPushNotificationHandler.js.map  7.28 KiB  [emitted] [dev]  [name: (api/sendPushNotificationHandler)]
            public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/sendPushNotificationHandler = api/sendPushNotificationHandler.js (api/sendPushNotificationHandler.js.map)
./api/sendPushNotificationHandler.ts + 2 modules 2.2 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "googleapis" 42 bytes [built]
external "axios" 42 bytes [built]
./ovs-app-firebase-adminsdk-b9hfq-04afa17dbf.json 2.24 KiB [built]
    + 4 hidden modules
Time: 7353ms
Built at: 2020-01-23 16:32:03
                     Asset      Size
      api/resetPassword.js  10.5 KiB  [emitted]        [name: api/resetPassword]
  api/resetPassword.js.map  39.5 KiB  [emitted] [dev]  [name: (api/resetPassword)]
public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/resetPassword = api/resetPassword.js (api/resetPassword.js.map)
./api/resetPassword.ts + 22 modules 21.2 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "fs" 42 bytes [built]
external "qs" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "mongoose" 42 bytes [built]
external "jsonwebtoken" 42 bytes [built]
external "bcryptjs" 42 bytes [built]
external "mustache" 42 bytes [built]
    + 4 hidden modules
Time: 8208ms
Built at: 2020-01-23 16:32:03
                     Asset      Size
     api/graphqlHandler.js  38.7 KiB  [emitted]        [name: api/graphqlHandler]
 api/graphqlHandler.js.map   102 KiB  [emitted] [dev]  [name: (api/graphqlHandler)]
public/reset-password.html  2.63 KiB  [emitted]
Entrypoint api/graphqlHandler = api/graphqlHandler.js (api/graphqlHandler.js.map)
./api/graphqlHandler.ts + 38 modules 63.1 KiB [built]
external "source-map-support/register" 42 bytes [built]
external "aws-xray-sdk-core" 42 bytes [built]
external "aws-sdk" 42 bytes [built]
external "http" 42 bytes [built]
external "https" 42 bytes [built]
external "apollo-server-lambda" 42 bytes [built]
external "apollo-server-plugin-response-cache" 42 bytes [built]
external "mongoose" 42 bytes [built]
external "apollo-server-cache-redis" 42 bytes [built]
external "ioredis" 42 bytes [built]
external "graphql" 42 bytes [built]
external "jsonwebtoken" 42 bytes [built]
external "bcryptjs" 42 bytes [built]
external "graphql-fields" 42 bytes [built]
    + 8 hidden modules
Serverless: Invoke webpack:package
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: aws-xray-sdk-core@^2.5.0, axios@^0.19.2, googleapis@^47.0.0, mongoose@^5.8.9, source-map-support@^0.5.16, ioredis@^4.14.1, bcryptjs@^2.4.3, jsonwebtoken@^8.5.1, mustache@^4.0.0, qs@^6.9.1, apollo-server-cache-redis@^1.1.5, apollo-server-lambda@^2.9.16, graphql@^14.5.8, apollo-server-plugin-response-cache@^0.3.11, google-auth-library@^5.9.1, graphql-fields@^2.0.3, node-rsa@^1.0.7
platform-sdk fetching: GET https://api.serverless.com/core/tenants/colorfy/applications/ovs
platform-sdk fetching: GET https://api.serverless.com/core/meta
Serverless: [serverless-jetpack] No matching service or functions to package.
Serverless: [serverless-jetpack] Packaging 0 functions, 0 services, and 0 layers with concurrency 1
Serverless: Packaging service...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: [AWS sts 200 0.479s 0 retries] getCallerIdentity({})
platform-sdk fetching: POST https://api.serverless.com/malt/destinations/create
Serverless: Invoke aws:common:moveArtifactsToPackage
```

Disabling the dashboard by commenting out the app and org fields from serverless.yml didn't make a difference

Serverless version:
```
➜  ovs-lambdas git:(master) ✗ sls -v
Framework Core: 1.61.3
Plugin: 3.2.7
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```

I'm assuming this might be a similar issue to https://github.com/FormidableLabs/serverless-jetpack/issues/67
