### ISSUE TITLE
Ignore if runtime is not node

### ISSUE THREAD

**Issue by thejuan** [FormidableLabs/serverless-jetpack#89]
I have a polyglot serverless service using jetpack.
On my python functions I setup
```
 package:
    individually: true
    include:
      - "!**/node_modules/**"
      - "!node_modules"
      - "!**/node_modules"
      - "!build"
```

However the node_modules still get added into the package for this function.
using exclude also doesn't work.
